name: Metrics

on:
  workflow_dispatch:
  push:
    paths-ignore: [ '*.md' ]
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Same config
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          user: SupianIDz
          config_timezone: Asia/Makassar
          config_output: svg

          # Stats metrics
          template: classic
          base: header, activity, community, repositories
          filename: metrics.svg

          # People plugin
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers

          # Habits & Lines plugins
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 31
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          # Languages plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Notable plugin
          plugin_notable: yes
          plugin_notable_filter: stars:>10
          plugin_notable_from: organization

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # Achievements metrics menggunakan fork sementara
      # TODO: Kembali ke lowlighter/metrics@master setelah issue #1706 diperbaiki
      # Issue: https://github.com/lowlighter/metrics/issues/1706
      - uses: stalomeow/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "Update `${filename}`"
          user: SupianIDz
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Makassar
          config_output: svg
          filename: achievements.svg
          repositories_batch: 5

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
