name: Metrics

on:
  workflow_dispatch:
  push:
    paths-ignore: [ '*.md' ]
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "Update `${filename}`"

          user: SupianIDz
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Makassar
          config_padding: 0
          config_output: svg
          filename: metrics.svg

          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers

  notable:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "Update `${filename}`"

          user: SupianIDz
          template: classic
          base: ""
          config_padding: 0
          config_display: large
          config_timezone: Asia/Makassar
          config_output: svg
          filename: notable.svg

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 31
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_notable: yes
          plugin_notable_filter: stars:>10
          plugin_notable_from: organization

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "Update `${filename}`"

          user: SupianIDz
          template: classic
          base: ""
          config_padding: 0
          config_display: large
          config_timezone: Asia/Makassar
          config_output: svg
          filename: achievements.svg
          repositories_batch: 5

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
