name: Change Height
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "height=\"383\""
          replace: "height=\"400\""
          regex: false
          include: "metrics.svg"
